spring.application.name=srs-analyzer
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/srs_analyzer_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:0329470859}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
llm.api.key=${LLM_API_KEY:AQ.Ab8RN6JYZSd0_BEH8efHyiyKOei993jWQCvDhcN48UGYNaElDQ}
llm.api.model=${LLM_MODEL:gemini-3.6-flash}
